name: Deploy to Google Apps Script

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Create clasprc
        run: echo "$CLASP_TOKEN" > ~/.clasprc.json
        env:
          CLASP_TOKEN: ${{ secrets.CLASP_TOKEN }}
      - name: Push Code
        run: npm run deploy
